name: CI

on: push

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn rune --version
      - run: yarn test
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn typecheck
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn lint
