name: CI

on: push

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn rune --version
      - run: yarn test
  test-docs:
    runs-on: ubuntu-latest
    env:
      TMPDIR: /tmp
      GAME_ASSETS_SSH: ${{ secrets.GAME_ASSETS_SSH }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - name: Install dependencies
        run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
        working-directory: docs
      - name: Build website
        run: |
          mkdir ~/.ssh
          echo "$GAME_ASSETS_SSH" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          yarn build
        working-directory: docs
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn typecheck
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn --prefer-offline --frozen-lockfile --non-interactive --ignore-scripts --silent
      - run: yarn build
      - run: yarn lint
