name: Update example games

on:
  workflow_dispatch:
    inputs:
      version:
        description: "SDK Version"

jobs:
  updateExamples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
      - run: yarn install
      - run: yarn updateExampleGames ${{ github.event.inputs.version }}